#+ORG2BLOG:
#+POSTID: 82
#+DATE: [2008-03-23 Sun 21:21]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Programming Language, Scheme
#+TITLE: Scheme in the Real-time CG Content Production

If you try to pin down Schemers to a particular stereotype, you will fail; they are just too diverse a bunch.

Take Shiro Kawai's [[http://practical-scheme.net/][website]]. He's got some great resources on that page. Dig in deeper and have a look at his paper [[http://practical-scheme.net/docs/ILC2002.html][Gluing Things Together - Scheme in the Real-time CG Content Production]].

The /short/ story is that



#+BEGIN_QUOTE
  Square USA R&D Team had been developing an in-house real-time rendering engine in a project called Dancer, and we adopted Scheme as an embedded scripting language.
#+END_QUOTE



Here is how they used it:


1. As a File Format
2. As a Debugging tool
3. For Rapid Prototyping
4. For Authoring



There are a lot, and I mean a /lot/ of really interesting bits about how the tackled the problems they were facing. 

The best part: you don't have to be a computer graphics buff to have a heck of a good time reading this paper. Enjoy!



