#+POSTID: 1822
#+DATE: [2009-02-18 Wed 01:52]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Programming, Scheme
#+TITLE: SRFI 97: SRFI Libraries

Thanks to the efforts of [[http://www.cs.brandeis.edu/~dvanhorn/][David Van Horn]] and the ratification participants; [[http://srfi.schemers.org/srfi-97/srfi-97.html][SRFI 97]]was produced. Here is the abstract:



#+BEGIN_QUOTE
  Over the past ten years, numerous libraries have been specified via the Scheme Requests for Implementation process. Yet until the recent ratification of the Revised6 Report on the Algorithmic Language Scheme, there has been no standardized way of distributing or relying upon library code. Now that such a library system exists, there is a real need to organize these existing SRFI libraries so that they can be portably referenced.

This SRFI is designed to facilitate the writing and distribution of code that relies on SRFI libraries. It identifies a subset of existing SRFIs that specify features amenable to provision (and possibly implementation) as libraries (SRFI Libraries) and proposes a naming convention for this subset so that these libraries may be referred to by name or by number.
#+END_QUOTE



Basically SRFI 97 makes it easier not only to reference SRFIs in R6RS but also to find out if they are even likely to be available.



