#+POSTID: 2773
#+DATE: [2009-04-25 Sat 14:32]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Build, Maven, Programming
#+TITLE: A Maven build number plugin

[[http://mojo.codehaus.org/buildnumber-maven-plugin/][Here]] is a plugin to:



#+BEGIN_QUOTE
  get a unique build number for each time you build your project. So while your version may remain constant at 1.0-SNAPSHOT for many iterations until release, you will have a build number that can uniquely identify each build during that time. The build number is obtained from scm, and in particular, at this time, from svn. You can then place that build number in metadata, which can be accessed from your app, if desired.

The mojo also has a couple of extra functions to ensure you get the proper build number. First, your local repository is checked to make sure it is up to date. Second, your local repository is automatically updated, so that you get the latest build number. Both these functions can be suppressed, if desired.

Optionally, you can configure this mojo to produce a revision based on a timestamp, or on a sequence, without requiring any interaction with an SCM system. Note that currently, the only supported SCM is subversion.
#+END_QUOTE





(via [[http://mail-archives.apache.org/mod_mbox/maven-users/200904.mbox/%3c49F1B3AB.6060407@gmx.de%3e][Maven]])



