#+ORG2BLOG:
#+POSTID: 5171
#+DATE: [2010-09-10 Fri 20:35]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: Books
#+TITLE: Chris's advice on how to read The Books of History Chronicles

1. The Circle Series (takes place in our world and in Other Earth)


   1. Green (Book Zero, sequel to Book 3 and prequel to Book 1. Best to read this last as it closes a lot of story loops.)
   2. Black (Book One) probably the best place to start with the BoHC world.
   3. Red (Book Two)
   4. White (Book Three)

   

2. 

The Lost Books (written for young adults, but still worth the read. Occurs mostly in Other Earth.)


   1. Chosen (takes place between Black and Red)
   2. Infidel
   3. Renegade (things make more sense if you read Showdown first)
   4. Chaos
   5. Lunatic (between White and Green)
   6. Elyon

   

3. 
 Paradise Novels (completely in our world)


   1. Showdown (other point to enter the BoHC world if you do not start with Black. But Black is a better place to start.)
   2. Saint
   3. Sinner

   

4. 
 Here are spin-off novels that occur due to events in the other series.


   1. Skin (spins off of Showdown, but is an independent book. Does have one "hook" for the Lost Books.)
   2. House (spins off of Showdown, but is an independent book)
   3. Immanuel's Veins (takes place in our world in the 11th or 12th century, but with ties to other books in the series)

   









My recommendation is to read Black, Red, White from the Circle first (this was the original Circle Trilogy that started it all)


1. Then read the Paradise Novels
2. Then read the Lost Books
3. Then read Green and the other independent spin-offs.








Based on the plot points that intertwine, I think things will mean the most if you read them that way.



