#+ORG2BLOG:
#+POSTID: 5471
#+DATE: [2010-12-26 Sun 14:37]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: philosophy
#+TITLE: Celtic Work Blessing

#+BEGIN_QUOTE
  May the light of your soul guide you.
May the light of your soul bless the work that you do
with the secret love and warmth of your heart.
May you see in what you do the beauty of your own soul.

May the sacredness of your work bring healing, light
and renewal to those who work with you
and to those who see and receive your work.
May your work never weary you.
May it release within you wellsprings of
refreshment, inspiration and excitement.
May you be present in what you do.

May you never become lost in bland absences.
May the day never burden.
May dawn find you awake and alert,

approaching your new day with dreams, possibilities and promises.

May evening find you gracious and fulfilled.
May you go into the night blessed, sheltered and protected.
May your soul calm, console and renew you.
#+END_QUOTE



(via [[http://www.care2.com/greenliving/celtic-work-blessing.html][care2]])



