#+POSTID: 5028
#+DATE: [2010-08-20 Fri 22:50]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: 22656, Concours, Kawasaki, Motorcycle
#+TITLE: Welcome New Connie Owners

Via [[http://www.mccainonline.com/motorcycle/new_connie_owners.html][John McCain]]:



#+BEGIN_QUOTE
  
This is a message I used to post to a Connie mail list monthly. If you just bought a Connie, it's got some pretty good tips that might help you.

We sometimes forget to welcome the new Connie owners here, especially if you don't introduce yourself by at least saying hi. I've been here a couple years and believe that the Concours owners community is one of the best things about this bike. It more than makes up for the "old" technology in my Connie. (well, I'd still like to have FI and hydraulic valves).

Here are a few suggestions, things I've learned along the way, that might help you enjoy your bike. Sometimes, I'm a slow learner, but these have sure helped me.

The first few things a new Connie owner should do while enjoying this great bike are (perhaps not in this order)...

1. Join COG (Concours Owners Group) http://www.concours.org . That gets you a great book of hints and tips (Best of Chalkdust) and fellowship (along with assistance) with some wonderful Connie owners. I've yet to attend an event other than a ride-to-eat meal, but rumors are that they're great.

2. Buy the official Kaw manual for the bike. Your Kaw dealer or ebay.

3. Buy a Clymers (or equivalent) manual for the bike. Any motorcycle shop or ebay.

I have both manuals, and as a beginning motorcycle mechanic, actually need both. Clymers gives step-by-step instructions for tasks, while the Kaw manual simply says "do it" in too many cases. But the Kay manual has more technical information (torque values and such) and covers some heavy mechanic'n better. You can often pick them up on ebay for 1/2 price... but it's worth paying full price for these.

4. If it's a used bike that didn't come with the owner's manual. Buy one. Read it a couple of times. Take notes. It contains lots of useful information. For example, there are adjustments to the front and rear suspension (that make a HUGE difference in the ride), location of accessory power points (in front and under the seat), and a maintenance schedule and how to find those hidden helmet locks.

5. Join the newsgroups/mail lists... Guess you've already joined at least one :). There are several worth noting:

Concourstech@yahoogroups (supposedly for more technical assistance type discussions). http://autos.groups.yahoo.com/group/concourstech/

Concourse Owners ( cog@micapeak.com ) for general questions and discussions (including sheep, tank bag clocks, and Connie sightings)

The COG forum at http://www.concours.org/forum/default.asp THE Connie owners' group.

Many of us only participate in one or two of these regularly, but there's a wealth of info in all of them. If you only participate in one regularly, it's worth checking the others from time-to-time.

6. Start doing your own maintenance if you have any mechanical aptitude or wannabe attitude. It's easy with those manuals, saves a ton of money, and there's plenty of help here. By saving receipts and making notes in a log, the warranty is honored if you do your own work, and you'll probably do a better job than most bike shops. If it's a used bike, you can start by replacing all the fluids and checking the maintenance items such as grease, air pressures, brake pads, etc.

7. Check out some of the commonly used references. This is my list, but there are also others out there. The regional COG sites are also often full of tips and tricks.

 * http://www.ldrider.ca/techpages Technical info and others' experience
 * http://www.automated-design.com/concours/parts.htm Generic part numbers
 * http://www.concours.org/list.faq.html COG technical pages
 * http://www.carveyparker.com/concours.htm Whoo Hoo's web Connie web page
 * http://www.mindspring.com/~gbyoung2/ Hidden under "Misc. Technical stuff" are some real gems.
 * http://home.austin.rr.com/mrandol/Connie/index.htm Has a great tire index amongst other technical musings
 * http://www.concours.org/sc/kawasaki\_ap\_manual.htm Here's a list of things that your dealer(if a new bike) or previous owner (if used) forgot to do. Go through this list and check this stuff. It's worth the time. 

There are so many Connie oriented web pages out there that Google returns 357,000+ hits for "Kawasaki Concours". You can consume a lot of time reading them when you should be out riding.

For any other questions, ask them on any of these mail lists or forums. Connie owners are a friendly bunch and a huge resource with lots of information from both the educational perspective and the practical experience perspective.

Oh, and I'm assuming that the Connie isn't your first bike. If it is, you have a bit of a steep learning curve. The Connie, with all it's great points, isn't known as an easy bike for the beginning rider. I can't imagine taking a DMV test on one, and it takes getting used to before you're comfortable at low speeds. So if you decided on a Connie as a first bike, get some serious riding instruction from a MSF type course. Sooner or later, you'll probably drop her, and that plastic IS expensive (but it can often be glued back together). Yes it's a tall, top-heavy bike, but she quickly loses that weight when you get her moving.

Enjoy your new bike! 

#+END_QUOTE







