#+ORG2BLOG:
#+POSTID: 5673
#+DATE: [2011-06-25 Sat 20:33]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: Motorcycle, Safety
#+TITLE: Radians Custom Earplug Review

Fed up with disposable earplugs becoming un-seated mid-ride, I figured that custom plugs would be the logical next step. Radians offers a very reasonably priced solution ($10USD) for custom so I ordered a set of the orange color.

The directions are straightforward, and I also followed the video on their site. The process was very simple. There is one thing that I would do differently next time. 

The material was very gooey. This was not really problem until I had to split the material up into halves; basically one half was bigger, so one plug looks a little bigger. In theory it doesn't make any difference because you can throw away excess material. In practice, I didn't notice the excess until it had "settled" and sort of looked funny, but I didn't want to mess with it at that point as it was already 10 minutes. In the future I would throw it in the fridge first to make the material more firm.

After that, my earplugs were ready, and the process was really easy. Then I tried them out and found that my custom plugs didn't work very well. I think that it has something to do with my ears.

What happens with my ears is that for earplugs to get seated right for me; I sort of have to perk my ears up. If you've ever seen someone move their ears, that is what I mean. My problem is that when I am riding and my ears perk up; the plugs get un-seated. This really isn't a problem with the plugs; rather I think they just won't work me. 

Having determined that holding my ears in that position 10 minutes is not realistic; I figured that I will stick with disposables for the near future.

Conclusion: while they didn't work for me, I'm sure that they would work for most people, they are a great deal and a no-brainer if you wear plugs more than a couple times a year.



