#+ORG2BLOG:
#+POSTID: 5635
#+DATE: [2011-03-18 Fri 22:38]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Motorcycle, philosophy
#+TITLE: Motorcycles Tell Us a More Useful Truth

#+BEGIN_QUOTE
  There is cold, and there is cold on a motorcycle. Cold on a motorcycle is like being beaten with cold hammers while being kicked with cold boots, a bone bruising cold. The wind's big hands squeeze the heat out of my body and whisk it away; caught in a cold October rain, the drops don't even feel like water. They feel like shards of bone fallen from the skies of Hell to pock my face. I expect to arrive with my cheeks and forehead streaked with blood, but that's just an illusion, just the misery of nerves not designed for highway speeds.

Despite this, it's hard to give up my motorcycle in the fall and I rush to get it on the road again in the spring; lapses of sanity like this are common among motorcyclists. When you let a motorcycle into your life you're changed forever. The letters "MC" are stamped on your driver's license right next to your sex and weight as if "motorcycle" was just another of your physical characteristics, or maybe a mental condition. But when warm weather finally does come around all those cold snaps and rainstorms are paid in full because a summer is worth any price.

A motorcycle is not just a two-wheeled car; the difference between driving a car and climbing onto a motorcycle is the difference between watching TV and actually living your life. We spend all our time sealed in boxes and cars are just the rolling boxes that shuffle us from home-box to work-box to store-box and back, the whole time, entombed in stale air, temperature regulated, sound insulated, and smelling of carpets.

On a motorcycle I know I'm alive. When I ride, even the familiar seems strange and glorious. The air has weight and substance as I push through it and its touch is as intimate as water to a swimmer. I feel the cool wells of air that pool under trees and the warm spokes of that fall through them. I can see everything in a sweeping 360 degrees, up, down and around, wider than Pana-Vision and than IMAX and unrestricted by ceiling or dashboard. Sometimes I even hear music. It's like hearing phantom telephones in the shower or false doorbells when vacuuming; the pattern-loving brain, seeking signals in the noise, raises acoustic ghosts out of the wind's roar. But on a motorcycle I hear whole songs: rock 'n roll, dark orchestras, women's voices, all hidden in the air and released by speed. At 30 miles per hour and up, smells become uncannily vivid. All the individual tree- smells and flower-smells and grass-smells flit by like chemical notes in a great plant symphony.

Sometimes the smells evoke memories so strongly that it's as though the past hangs invisible in the air around me, wanting only the most casual of rumbling time machines to unlock it. A ride on a summer afternoon can border on the rapturous. The sheer volume and variety of stimuli is like a bath for my nervous system, an electrical massage for my brain, a systems check for my soul. It tears smiles out of me: a minute ago I was dour, depressed, apathetic, numb, but now, on two wheels, big, ragged, windy smiles flap against the side of my face, billowing out of me like air from a decompressing plane.

Transportation is only a secondary function. A motorcycle is a joy machine. It's a machine of wonders, a metal bird, a motorized prosthetic. It's light and dark and shiny and dirty and warm and cold lapping over each other; it's a conduit of grace, it's a catalyst for bonding the gritty and the holy. I still think of myself as a motorcycle amateur, but by now I've had a handful of bikes over half a dozen years and slept under my share of bridges. I wouldn't trade one second of either the good times or the misery. Learning to ride one of the best things I've done.

Cars lie to us and tell us we're safe, powerful, and in control. The air-conditioning fans murmur empty assurances and whisper, "Sleep, sleep." Motorcycles tell us a more useful truth: we are small and exposed, and probably moving too fast for our own good, but that's no reason not to enjoy every minute of the ride.
#+END_QUOTE


-- Unknown

(via [[http://groups.google.com/group/milvinmoto/browse_thread/thread/7756dc40a98a4c54][MilVinMoto]])




