#+POSTID: 6154
#+DATE: [2012-01-25 Wed 04:06]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: Endometriosis, Research
#+TITLE: Comments on ENDOMETRIOSIS: EMERGING RESEARCH AND INTERVENTION STRATEGIES

[[http://en.wikipedia.org/wiki/Endometriosis][Endometriosis]] is an interesting disease. Wiley publishes the proceedings of a conference on endometriosis entitled "ENDOMETRIOSIS: EMERGING RESEARCH AND INTERVENTION STRATEGIES" [[http://onlinelibrary.wiley.com/doi/10.1111/nyas.2002.955.issue-1/issuetoc][here]]. The proceedings cover a breadth and depth of topics that were all very interesting. 

Here are the things that really jumped out at me:


-  Endometrium are likely to be present outside the uterus of most women; but not all of them have pain. Pain is the thing that makes it a disease from which women suffer.
-  Research demonstrates a impact in fertility of primates; but not humans.
-  The definition of stages of the disease depends on the depth of which the endometrium have penetrated the tissue. This is surprising because it has nothing to do with the amount of pain suffered.
-  The menstrual cycle itself is an amazing thing.
-  A vicious circle occurs where endometrium begin to "fuel their own fire".
-  The immune system's failure to "clean up" ectopic endometrium is part of the problem.
-  There are number of things that can be measured in regards to the disease and it's process.
-  The disease has traits of an auto-immune disease; and women with it are more likely to have other auto-immune diseases.



The papers within that report are the first research I've ever read on the topic.



