#+ORG2BLOG:
#+POSTID: 6853
#+DATE: [2012-12-29 Sat 03:31]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Motorcycle, Resource
#+TITLE: Bring a trailer

#+BEGIN_QUOTE
  Barn finds, rally cars, and needles in the haystack...

We put together [[http://Bringatrailer.com][Bringatrailer.com]] because finding great vintage cars online has become too much of a hassle. There is no need to keep sifting through hundreds of hopeless projects or overpriced dealer inventories to find that one car you've been looking for. We pick the winners and save you the trouble... the best bargains, the best dream cars, and the best rarities.

We especially favor regularly driven real-world classics, and cars with well chosen period-correct modifications. We'll usually skip the blue chip restorations and trailer queens unless they offer something amazing in aesthetic or rarity. Deep pockets can buy a big-dollar restoration but they can't buy good taste or driving passion.
#+END_QUOTE


-- via MilVinMoto via bringatrailer.com



