#+ORG2BLOG:
#+POSTID: 7146
#+DATE: [2013-02-13 Wed 02:49]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: 02947, CB750, CB750F, Honda, Motorcycle, Repair
#+TITLE: CB750F: Day 14

Scott the parking attendant said hi. Tonight I cleaned the float seals. I should have attached a q-tip to a drill like Tim said, it took forever, but was worth it, and the Brasso helped. You could even read little symbols on the brass float passage itself. The puck covers all had this tacky material on them; not sure whether it was oxidation or what. Installed the pilot screws according to the original measurements: 2.5, 2.39, 2.62, 2.5 (turns back out). Did the float bowl leak test, and blew them out with compressed air including the drain screw afterwards. Next time it will be the float valves and bowl installation. After staring at the float values for while, I wondered if they should be replaced after one of them got stuck recessed. The ultrasonic cleaner continues to serve diligently; but doesn't need any more photos at this point.

[gallery ids="7147,7148,7149,7150,7151,7152,7153,7154,7155,7156,7157,7158,7159,7160,7161,7162,7163,7164,7165"]



