#+POSTID: 9194
#+DATE: [2014-09-26 Fri 15:40]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: philosophy
#+TITLE: Use your space appropriately


When facing a decision of how to utilize space it is sometimes easy.
Choosing between allocating land for a water purification plant vs
a donut shop might not be an easy choice but it is an obvious one.
How then do we allocate our internal or mental space?







Inside us the space is limitless. Most of the time though we don't feel that way.
Instead there seems to be little free space, and that results in a feeling of
being overwhelmed and unable to cope with life. That is normal and all humans
experience this phenomenon.







The good news is that we are in charge of our internal landscape. Even better,
it is always with us! We can tidy it up whenever wish. We can open up more space.
Perhaps it is more like discovering it then opening it up, because it is already there.







That new space can help to accommodate new investments, like learning how to knit
for example. It may also simply be observed, and left alone. That is really
helpful for "making space" for all of the surprise trials that inevitably will
occur in life. Usually they aren't very surprising though, given the nature of
this reality. Nonetheless, it makes *everything* easier when you have a *lot* of
/room to breathe/!







