#+POSTID: 8540
#+DATE: [2014-05-12 Mon 00:31]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: philosophy
#+TITLE: Anywhere but here

We've all said it at one time or another...



#+BEGIN_QUOTE
  
I would be rather be anywhere but here.

#+END_QUOTE



Regardless of how long we ruminated upon this feeling, there is someone who thought about it much longer whan we did: our mind.

When did it lose its taste for the sweetness of the present? Always running to the future to chase how things could be; or dragging us into the past to obsess over just how great things once were. As a passenger, it feels more like being dragged along side of a train trying to reach its illusory and imaginary destination, then any nice sort of ride up in first class with a cup of chai and a fruit tart.

Teaching our mind to serve us, to listen to the real source of wisdom, within, is the single most important thing that any of us may every strive to accomplish.



