#+ORG2BLOG:
#+POSTID: 9175
#+DATE: [2014-09-23 Tue 20:04]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: R-Project
#+TITLE: quantmod  Quantitative Financial Modelling & Trading Framework for R

#+BEGIN_QUOTE
  The [[http://www.quantmod.com/][quantmod package]] for R is designed to assist the quantitative trader in the development, testing, and deployment of statistically based trading models.

What quantmod IS

A rapid prototyping environment, where quant traders can quickly and cleanly explore and build trading models.

What quantmod is NOT

A replacement for anything statistical. It has no 'new' modelling routines or analysis tool to speak of. It does now offer charting not currently available elsewhere in R, but most everything else is more of a wrapper to what you already know and love about the language and packages you currently use.

quantmod makes modelling easier by removing the repetitive workflow issues surrounding data management, modelling interfaces, and performance analysis.
#+END_QUOTE







