#+ORG2BLOG:
#+POSTID: 8501
#+DATE: [2014-05-01 Thu 15:26]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Link
#+TAGS: Emacs, Ide, OSX, Utility
#+TITLE: Simple OSX key swap and trackpad ease

[[http://batsov.com/articles/2012/10/14/emacs-on-osx/][This]] article describes a [[https://pqrs.org/macosx/keyremap4macbook/document.html.en][tool]] for remapping your Mac laptop keyboard. Initially I took the simpler route and swapped caps lock with control and command with option in the system preferences menu. That was OK until I remembered that I had wanted to have a right control key on the laptop. Oops. 

The solution was simple, installing KeyRemap4Macbook and checking a single setting, *Command\_R to Control\_L* was all it took. Thanks Bozhidar!

Now you may have been daunted by the configuration menu but take it as an opportunity to learn about some valuable ways to configure things. What was delightful for me to learn about was its [[https://pqrs.org/macosx/keyremap4macbook/document.html.en][Multi-touch extension]] feature (sorry no direct link) which is based on [[http://www.sonycsl.co.jp/person/rekimoto/tsense/soft/index.html][ThumbSense]]. Very cool and very nice looking if you want to enjoy a trackpad without having to contort your hands just to get a mouse click (if you don't have a Macbook of course).



