#+POSTID: 9787
#+DATE: [2015-06-11 Thu 01:38]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy
#+TITLE: The Opportunity in Embarrassment

"Embarrassing" is an adjective. It classifies things that cause shame to a person. The act of being embarrassed is composed or 3 parts.

In the first part one learns something new about themselves. Generally learning new things about oneself is a pleasant and exciting process. That thing that was just learned was not expected at all by the subject. It is new and surprising information. Generally learning new and surprising things are fun. The third aspect is where the subject decides that the new information is shameful in some way. The first two parts of the process are really neat and fun and the third part is horrible. This is where the opportunity lies.

When you reach the 3rd part stop yourself. Determine whether it is you, or your mind, that has decided that you should be ashamed. It is probably your mind. Only your mind would say that "in fact, 2 outta 3, is bad". That is negative and crummy. If 67% of the situation is good then stick with that.

Every time you become embarrassed take it as a delightful opportunity to ignore your negative mind and tell it instead to cheer up and enjoy this opportunity for self-transformation that just appeared in front of you.




