#+ORG2BLOG:
#+POSTID: 9532
#+DATE: [2015-02-09 Mon 19:46]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: Fitness, Happiness, Health, Learning, Yoga, philosophy
#+TITLE: First Hatha at YogaOne @yogaonemke Fox Point Report


On Sunday I attended the "Vinyasa Flow L1-2" class. [[http://www.yogaonestudio.com/connect/#instructors][Catherine]] taught it in [[http://www.yogaonestudio.com/connect/#foxpoint][Fox Point]]. This was my first class in a long, long time. Too long. It was so great to get back.







Catherine is a delightful teacher and she taught a delightful class. Let me elaborate.







I haven't done hatha for a long, long time. Too long. I really haven't done much of anything physical for a long time, either. That is the problem. No, that is the opportunity. Everything is either an opportunity, or not worth pondering.







I went to class without a clue about how I was going to get through 60 minutes of hatha. I mean, I knew that I couldn't. I banked on being able to just stop and rest. I did, and that was fine.







I needed help overcoming the inertia of doing nothing, and this was my chance, so with a gentle nudge from my good friend to help me along, I went, even though people would probably figure out pretty quickly that I wasn't attending class as my warm up for my Cirque du Soleil interview later that morning.







Nobody chased me out of the studio, it was no big deal. I didn't run away from the whole thing, either. I did hatha for 20 minutes, rested for 20, and did the final 20, and that was no big deal. The last 20 was a lot easier floor stuff. The world didn't end. Instead, the world expanded.







Could somebody going to yoga be embarrassed about being clueless? Yes. Could they be insecure about the whole thing? Yes. Might they wonder why the heck they are there when, everyone else there seems to be an expert already? Yes. I didn't think any of it, though.







My mind didn't even bother to start telling me those stories. Catherine created an environment where the minds of her students could be illuminated by the luminosity of that which is gentle and kind, so that they could just do their practice. There is work to be done, and you have to be the one to do it, but when you have a kind and masterful teacher, it is a delightful experience because you can utilize your energy for your own good, instead of your own detriment with doubt and fear. Catherine was super.







The whole thing was really, really great. I'm going to the beginner classes next, with the goal of working on strength and flexibility. Part of me wonders of some beginner-yoga motorcycle-riders classes will spontaneously be scheduled as Spring nears.







