#+ORG2BLOG:
#+POSTID: 9421
#+DATE: [2015-01-12 Mon 01:16]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Article
#+TAGS: philosophy
#+TITLE: Every definition is a constraint


Every definition is a constraint.







Primarily they define operational limits of this reality. Even defining something to be "limitless and without constraint" is limiting because it requires either the written or the spoken form (albeit both spatial) and doesn't allow for other possible means of communication.







The basis of most forms of science is definition, and thereby, observation.







Artistic expression is both a definition, and, an expression. Because it occurs within the operational constraints of this reality, it is by nature constraining and limiting. This is counter-intuitive, and, quite surprising. Perhaps this is already quite clear to those who have experienced things which are beyond definition?







Perhaps your are familiar with this phenomenon where in the attempt to define those things, you, quite unintentionally, tarnish and drag down those things. It is quite a bitter-sweet experience when you do want to share them, due to the sheer joy of it, and find that you simply can not.







You may have a feeling that you are not sharing, but, you must quite seriously ponder the question of "How can you withhold that which is intrinsic to every human being and is their birthright in this universe?".







