#+BLOG: wisdomandwonder
#+POSTID: 10021
#+DATE: [2015-09-20 Sun 16:09]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Link
#+TAGS: Editor, Emacs, Ide, Learning, Literate Programming, ML, Programming Language, Reproducible research, Research, SML, Standard ML, Teaching
#+TITLE: A Book Produced Using Org

[[https://lists.gnu.org/archive/html/emacs-orgmode/2015-09/msg00605.html][Via:]]

#+BEGIN_QUOTE

I am happy to share with fellow Orgers my recent book — Ending Malnutrition:
from commitment to action — published by the Food and Agriculture Organisation
of the United Nations, Rome and Tulika Books, New Delhi
(http://www.fao.org/3/a-i4921e.pdf), The book was written and produced entirely
in Org.

This would not have been possible without the terrific support provided by this
community. Over the last few months, I have come to this mailing list with
several queries about how to do something or the other, and people have very
patiently provided solutions and suggestions.

I would like to thank everyone for their patience and their support.

Vikas

--------

From acknowledgements of the book:

In addition, for all the statistical work and writing, the authors relied on R
([[http://www.r-project.org][www.r-project.org]]), org ([[http://www.orgmode.org][www.orgmode.org]]), and LaTeX. All three are open source
projects, freely made available by very vibrant communities of developers.
During the course of the work, we often drew on support from these communities.

#+END_QUOTE
