#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10445
#+DATE: [2016-10-15 Sat 18:56]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Sense, Happiness
#+TITLE: Miracles Without Expiration Dates

Do you have a story about a miracle that you personally experienced? A lot of
us do. Even if you don't, you might have a friend or family member close to
you that shared their story. The surprising thing about everyone's experience
here though is that the experience itself is easily forgotten!

It is a surprising attribute. Miracles are /supposed/ to change your life for
the better. They are supposed to inspire you to change your lives, and the
lives of others for the better. They are supposed to be deeply meaningful, but
in the end… they are not. In fact, they might not even be memorable. There is
some comfort here though, and that comfort resides inside *you*.

Everyone human contains a unique property in this world: there is no one like
them and they are here for a reason. That is miraculous. That miracle is
inside of them and it is always with them. That miracle is untarnishable and
it has an even more important property:

That miracle inside of you hasn't got an expiration date. You will never
forget about it. To simply be who you are in this world is to share it. There
isn't anything that you need to tell anyone about it.

You are your own miracle without an expiration date. It is the sole reason for
your having taken birth as a human. Your job is to figure out that reason and
start living it as quickly as possible.
