#+BLOG: wisdomandwonder
#+POSTID: 10288
#+DATE: [2016-06-17 Fri 15:13]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Sense, Happiness
#+TITLE: The Opposite of Numb is Sense

I've got a favorite story. It has been for a long time. I've always wondered
why and you probably will too once you hear it. I was born in Milwaukee, WI.
My parents moved to Reedsville, WI to run a funeral home when I was a baby.

We lived in a wonderful old home. My parents had a station wagon. Eventually
they had a Datsun Nissan Sentra hatch-back; the car with three names. The
other one was a Family Vacation style station wagon.

What happened one day was that dad was driving, mom was in front, and I was in
back. We got home and got out of the car. Not paying attention, I managed to
get my fingers squashed between the car and the car door when my mom closed
it. My mom didn't notice though; because it didn't hurt me. I stared at it
wondering what was going on. I told mom and she opened the door. That is when
the surprise came!

When the blood rushed back into my fingers I could barely make sense of it. It
was confusing, and even exciting, all at once. It felt like suffocating, and
then drowning, and then burning. My little mind said "Oh, OK, hmm..." and then
things got really strange: then the pain came.

It enveloped by entire being; the prickly pain of a thousand tendrils of angry
fire. The world stopped if only for a microsecond. Then it started again. Then
the tears came. Mom hugged me. But, I couldn't shake this one off. It took the
rest of the afternoon to feel better. This is probably normal.

The reaction, I mean. It was all so sudden and the process was so quick.
Little people have that strength of being able to go through the process in
seconds or hours instead of years like big people. Big people can even end up
forgetting what got them into that numb place so by the time they get back to
sensing again it is even more baffling. The challenge is that all of the
stages and feelings still come along with it. It can be baffling.

There you are happily plodding along in life as numb as can be and you start
to feel the burning. It is shocking! Electric, truly.

The fun and glorious parts of the process get a lot of love and attention.
Maybe these parts deserve some credit, too? Not to dwell on them, but maybe
just recognize them as part of the process?

Being able to feel yourself take a great big breath of air, and exhale it,
whenever you want, makes it all worth it.

Doing it for that little person version of yourself that is tucked safely away
in the infinite space of your own heart so they can breathe easy makes it all
worth it, too.

#  LocalWords:  Reedsville Datsun Sentra
