#+DATE: [2016-09-05 Mon 14:21]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Sense, Happiness
#+TITLE: Men, Trauma, Rage And A Path To Wholeness

Trauma has two parts. The first part is when you experience events that exceed
your emotional capacity.

#+HTML: <!--more-->

You can be one month old and accrue trauma when you don't get fed in time. It
is true; that /does/ fit the definition. You can accrue trauma when you are one
year old and you don't get to eat that entire chocolate bar despite your
biggest wails. This *isn't* to diminish trauma survivors rather it is a place to
start making sense of the mechanics of trauma. As we grow older the
opportunitie for trauma typically grow in diversity. All of those events
result in the same aftermath; retaining the even within our nervous system.

Our nervous system is the storehouse for trauma. It works differently than a
memory. Memories are /recalled/ in a slightly diminished form. That doesn't make
them pleasant, but it does make them /palatable/. Those memories exist without
the shame, sharp edges, and vivid brutality. Often they are accompanies by
observations that come in the form of "And now there are better times" or
"And I remember the people who helped me… God bless them" or "If you could
meet my friends who helped me get though it… they are the salt of the Earth".
Those observations and softening of the memory are a dead giveaway because
they reveal that the survivor's internal state has change from *re-living* the
event to sharing something new that came out of that event. For (those who
identify as) men though, that process of transformation, the /second/ part of
trauma, is next to impossible because modern men have one emotion allowed for
the expression of their emotion (their emotional vocabulry): rage.

Rage is an impotent emotion that is part of the human experience. Rage's
limited scope conveys shock, horror, anger, compassion, and an urgent call to
action. By definition, it's scope *must* be limited. 
