#+DATE: [2016-09-05 Mon 14:21]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Sense, Happiness
#+TITLE: Men, Trauma, Rage And A Path To Wholeness

Trauma has two parts. The first part is created when you experience events
that exceed your emotional capacity.

#+HTML: <!--more-->

You can be one month old and accrue trauma when you don't get fed in time. It
is true; that /does/ fit the definition. You can accrue trauma when you are one
year old and you don't get to eat that entire chocolate bar despite your
biggest wails. This isn't to diminish trauma survivors experience, rather it
is a place to start making sense of the mechanics of trauma. As we grow older
the opportunities for trauma typically grow in diversity. All of those events
result in the same aftermath; retaining the event within our nervous system.

Our nervous system is the storehouse for trauma. It works differently than a
memory. Memories are /recalled/ in a slightly diminished form. That doesn't make
them pleasant, but it does make them /palatable/. Those memories exist without
the shame, sharp edges, and vivid brutality. Often they are accompanied by
observations that come in the form of "And now there are better times" or
"And I remember the people who helped me… God bless them" or "If you could
meet my friends who helped me get though it… they are the salt of the Earth".
Those observations and softening of the memory are a dead giveaway because
they reveal that the survivor's internal state has change from *re-living* the
event to sharing something new that came out of that event. For (those who
identify as) men though, that process of transformation, the /second/ part of
trauma, is next to impossible because modern men have one emotion allowed
in their emotional vocabulary: rage.

Rage is an important emotion. Rage's limited scope conveys shock, horror,
anger, compassion, and an *urgent call to action*. By definition, it's scope
makes for a painfully limited budget of expression. When your only currency is
rage though, there isn't a lot to buy with it and it often has comical results.

When you only have rage, and you notice that you forgot to turn the light off
when you are already heading out of the door, you see the light-switch and say
"you bastard". Hilarious, right? We've all had it happen. Think of another
example of how young men relate to each other with nothing more than "You
m*****f*****'er" and "F*** you…" for the most simple and mundane interactions
like when one of them is upset that the other didn't take the trash out. Ever
heard a conversation in that context like "When you didn't take the trash out,
I felt disappointed because we have a plan of alternating that responsibility
and also I'm under the weather and…". Probably not. Men get one emotion to
express things: rage. This turns into a double-edged sword.

Wanting /some/ range for emotional express, they've only got two other options
left: either turn the rage down to one or *turn it up to eleven* (guitar
amplifier analogy of output volume). Here is how it usually goes:

First, men become indifferent and disinterested. This is a common complaint.
They just don't seem to care or get engaged. This is a major symptom for young
men today. It is almost blown off as "teenage doldrums" and "that is just what
young men do". No way, I don't buy it. I grew up with some of the most
thoughtful and kind young men you could find anywhere. Same goes for those
young men who grew up who became disinterested men, too. It doesn't add up.
Nothing good seems to come from this approach, but it part of the only
emetional range allowed for them.

When you only have on emotion, you have to funnel everything into that. Men
get rage. They get either the minimum or maximum. The minimum makes them go
numb. Numbing means that they don't have access to anything useful information
from their experience. This is typified (or symptomatic) of being "Out of
touch, disinterested, and not present". Now compare that with turning to the
opposite extreme.

When they want to feel *anything* they have to push that rage further. Numbing
results in pushing things to extremes just to /attempt/ to feel anything. You
have to go to extremes to even feel anything; causing more problems.

The actions sports gotta be extreme. The horror films gotta have more gore.
The grind core music has gotta be harder. The porn has to be harder. The sex
has to be riskier. Those are the easy ones. It is the words that are the worst
because the words have to be more hurtful and destructive. The words have to
be so strong and abrasive in order to say *anything*. All of those words add up
to just about zero. Fortunately there is a place that on the path that exists
beyond those words where the journey to wholeness can begin.

When a man shares his trauma he is inviting you into a sacred place. It is a
three dimensional place that is more secret and private then you could ever
phantom. First of all, he is barely OK being there himself. It is ground-zero
for all of his shame, and guilt and failure. When you go there, reverence
comes to mind. Not reference for the traumatic event, but rather, reverence
for his courage. He is laying bare to you that part of himself that he
*cannot accept*. It is the part of himself that has no home, that is incapable
of being loved, and simply has no justification for existence. When you have
this opportunity, often the best response is silent thanks and attention
because you are unlikely to ever be there again. That is for a good reason, and
unfortunately leads to a secondary problem.

When trauma is shared, it is a private and wholesome thing. It is part of
grieving and it is part of acceptance. Often the guest is a participant in
that healing. The whole event is wholesome and helpful. It contains an
unintuitive property though in that all of the value is contained within that
first sharing and every sharing after that not only diminishes the value of it
but also makes things more difficult for the survivor. The first time it is
shared, it helps a lot. Every single other time it is shared makes things
worse, fast. That is where the opportunity lies: when you are invited to that
place don't bring your dirty shoes onto that sacred ground and just be there.
That is all it takes. That is what helps the survivor start walking a new
path. Part of being a friend is walking with them on that path free of
judgment and failure. That is the path that leads the survivor back to
wholeness.

Yoga means "union". That is one of the most popular definitions of it. It is
often presented in grandiose, glorious, and frankly magical terms. Most of the
time that makes it inaccessible to ninety-eight percent of us and that is a
shame. It is a shame because the *union* to which it is referring is
/the unification of the disparate parts of ourselves that we cannot accept/.

That part of ourselves that did the despicable. That part of ourselves that
did the unthinkable. That part of ourselves that is worthy of death. That
comes off a bit strong, doesn't it? Let me share with you what it means
/to be a man/ though.

A story comes to mind here from Hemingway's _In Our Time_. The story titled
"Indian Camp". In it the protagonists father, a doctor, is called to a Native
American reservation because a woman is going through a breech birth.
Dutifully the Dr. (dad) assists the woman despite her horrifying screams that
are horrifyingly revealing her brutal pain. The husband lays in another bunk.
The whole passage initially reads oddly.

Dad performed the C-section with basic tools and it went well; the baby was
delivered, survived, and so did mom. Dad, despite the horrible situation and
brutal cries was truly a great man and was commended as such "you're a great
man, all right". Contrast that with the husband. Called on to see his new
child we find that he has slit his own throat. Shock and horror struck me here
and I couldn't make sense of this for twenty-eight years. Now I do though and
I can thank Brene Brown.

Brene Brown is a genius. She shared a story once. The story was about a man
who attended a book signing. He asked her to sign four books; one for his wife
and three for each of his daughters. She did and then he asked her "So, why
don't you every deal with men's experience?". She replied something to the
effect that she hadn't and there was no malice in it. He replied something
like "Well, that is convenient, because let me tell you how it is for me
expressing my feelings: my wife and daughters would rather see me die then
fall off my high horse, their shining knight in armor". That floored me. It
floored me.

It is twenty sixteen. The hold days are supposed to be gone. Hemingway wrote
about men who would rather die then cry. This man bared his soul for exactly
the same pain that all men face: either repress all emotions, or die; that is
what it means to be a man.

I object, my friends. There are more options. Great friends are options.
Kindness is an option. Embracing more emotions than rage is an option. They
are all part of it. For me yoga is an important part of it in a way that I
never expected.

Yoga today is popular and I am glad for that. I am child of "The New Age" (did
you hear that it ended, I was shocked!). It was always about eating right and
meditating and doing hatha and studying. Great stuff, and none of it ever
clicked for me. Maybe I was too lazy? (I am). Maybe I wasn't a good student?
(I'm not). When my world came crashing down those, it was there for me. All of
the little things like diet and meditation that seemingly don't amount to much
yet give you breathing room and hold your head high above the water. The
people, too, who never leave. Those people who never pull you toward them; but
never push you away when you ask for their help. Those Yogis are not limited
to the ones from the tradition into which you were initiated. They are
everywhere. They are friends and family and even strangers. They are people
who come from the unbroken lineage of the Yogic tradition that expands deep
in the limitless cave of our heart which can never be broken. That care deep
in our hearts is universal and united with everyone, and it makes it special
to be alive as a human. They expect nothing. Just like our nervous system
expects nothing, same goes for them. All of them and everything exist to give
you a little space; a little room to breathe. Maybe you grow; maybe not. It
doesn't matter. What matters most is that you heart comes back together from
the millions pieces into which it had been shattered. It is never too late.

It is never too late to be whole again. It is never too late to be happy
again. It is the birthright of every human being to fulfill the reason why
they came to this Earth. If you can serve a another human being in that
mission, whether they ever know it or not (it's better if they don't), then
you are doing that which ought to be done.

Hear, hear! Now is the time do it for yourself, too.
