#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10343
#+DATE: [2016-08-07 Sun 21:30]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Sense, Happiness
#+TITLE: Respecting Your Limits Means Respecting Yourself

Accepting yourself for who you are doesn't always mean respecting yourself. If
you identify as male, then you are especially suspect here: part of being a
person who identifies as male today means that you only compare yourself to
the top 1%. The cult of exceptional-ism is strong, alive, and well today.

#+HTML: <!--more-->

Part of its strength is in its secrecy. That includes the dismissive chuckles
and grunts men use to laugh off their pain. That includes whatever works to
make things numb. That includes shoe-horning their pain into the one vehicle
that is socially acceptable: rage. Secrecy, numbing, and rage have surprisingly
similar effects: virtually nothing useful combined with a gaping well, an
endless pit to try and cram the pain down into hoping never to see it again.
Unfortunately, we will.

Beneath the pain, though is resolution. Resolution comes from being able to
feel things again and there are noticeable steps. Specifically you will start
to come to terms with your limits, whatever they may be. The delightful thing
is that your limits do not define you. They are simply operational
parameters. They are lines on the side of the road or barriers on the side
of a cliff. Stay within them and enjoy your ride; exceed them and suffer
appropriately. Limits say absolutely nothing about a person and anyone who
tells you otherwise is lying. Two things happen when you start to respect your
limits.

The first is that you start to enjoy life, maybe for the first time ever. When
you operate within your means, you have energy at the end of the day and to
start the next day. No more going to be exhausted and waking up exhausted,
too. You start to understand that happiness doesn't require a herculean
effort, instead it requires a thoughtful effort, and therein lies the major
shift (and second thing).

The second thing is that you will have to pay attention to yourself. Living
within your limits means that you have to respect them and therefore respect
yourself. Whatever you think you are; you are wrong. Whatever stories you tell
about yourself; you are wrong. You are a perfect and unique human being here
to do something that only you know in your heart to be true. Nobody can tell
or convince you otherwise (if they do they are wrong). Paying attention to
yourself might feel like a herculean effort, but that is only because you
probably have never done it before. Male culture demands this, so, don't take
all the credit for yourself on this one.

Kudos to you for bucking the trend, here. Kudos to you for standing up for
you, when maybe no one else ever did for you, before. Most importantly, maybe
you never did before, either. It is OK though because you probably had really
good reasons. Maybe they were reasons that made sense to a three year old.
Maybe they were reasons that made sense to a nine year old. Maybe they were
reasons that made sense to a sixteen year old. It doesn't really matter. All
that matters is that you revisited them and gave yourself the room, space,
love, and acceptance to reconsider the decisions that you made (consciously or
not) so long ago.

Respecting your limits means respecting how you are to live in a way that lets
you be the best person that you can be here and how with all of your perceived
flaws and imperfections because in practice everyone is actually a perfect and
delightful human being trying to discover who they really are on this planet.

#  LocalWords:  horning
