#+BLOG: wisdomandwonder
#+POSTID: 10462
#+DATE: [2016-10-16 Sun 13:48]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Sense, Happiness
#+TITLE: The Ultimate Meditation Hack

A lot of us meditators feel like we can't get our feet off the ground when it
comes to our meditative practice. Typically it goes something like this:

- Meditate thirty minutes per day
- For seven days
- Then, never meditate again for six months
- Finally, the beginning and try again

Actually, that is fine because /practice is practice/. There is an easier way
though that I call the /ultimate meditation hack/.

#+HTML: <!--more-->

The most important thing that you can do is to do your practice at the same
time every day. Ideally: twice a day. From there the hack is really simple:
choose the single unit of time that you are willing to meditate in one
sitting. Say you start with one second. When you meditate the second time that
day, add the same unit of time to your current total meditation time. The
first day you will start with one second and the second time you meditate you
will be at two seconds. On the second day you will start with three seconds
and finish the day with four seconds. The rocking thing about this approach is
that most minds will never argue with you about meditating for one second.
Actually I am being more specific here: I mean *your* mind. It will not object
to one second.

As the days go by, you will make progress before your mind knew it. In fact,
it will never notice. It will just be happier that you are doing your
respective practice.

If you are eager, start with fifteen seconds. If you are really eager, start
with one minute. One minute is my favorite starting point because it doesn't
seem like much and it has fast gains. Think about it, by the end of one month
you'll be meditating for sixty minutes at a time. One whole hour! For those of
you like me who were baffled by how anyone could meditate for sixty minutes
straight you will be delighted to find the answer: start small!

That is the ultimate meditation hack.
