#+BLOG: wisdomandwonder
#+POSTID: 10534
#+DATE: [2017-03-26 Sun 09:59]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Health
#+TITLE: What To Do When Paper Tape or Band-Aids Pull Your Skin Off

/Your/ skin is sensitive. After every kind of medical procedure ranging from
drawing blood to performing surgery your wound is covered using gauze held on
by paper tape or some kind of Band-Aid. Eventually the wound heals and now
comes the time to remove the tape. Some people are allergic to the glue in the
tape. When the tape is removed it can pull off the skin leaving at least a
"burn" and a most a deep groove that horribly hurts and takes weeks to heal.
Fortunately there is a solution:  Mepilex Border Lite Foam Dressings.

#+HTML: <!--more-->

They are a like a dream come true. The tape is safe for your skin. It
minimizes the pain and skin damage when you change the dressing. Instead of
forcing you do keep your body in a single inflexible position so the dressing
won't fall off it is flexible and comfortable. To reiterate it is
hypoallergenic so for a lot of you your skin will be safe. Last and most
important: when you remove it your skin will remain intact. In other words: it
will not pull your skin off.

If you have to deal with things like this then just ask your caregiver to use
this as a dressing. Nearly every caregiver has it but they only use it if you
ask for it. It costs a tiny bit more for them. Well if you are already there
then you are already going to spend a ton of money so why not save your skin?
It is beyond worth it. There are a bunch of sizes and at home the [[http://amzn.to/2npB1cj][3"x3"]] and
[[http://amzn.to/2nTEoJO][4"x4"]] cover just about everying. Everyone needs to know about it.

Tells your family. Tell your friends. Tweet about it. Facebook about it.
Everything. It might not sound like a *big deal* but if you are the one getting
your skin pulled off then you will be thrilled about a product like this!
