#+BLOG: wisdomandwonder
#+POSTID: 10616
#+ORG2BLOG:
#+DATE: [2017-07-24 Mon 07:57]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Happiness,
#+TITLE: Just Because I Believe It Doesn't Mean It's True Or Good To Do

Just because I believe it doesn't mean it's true. The more I test this out the
more I am surprised. Now my state of surprise proves nothing. Sometimes I love
getting surprised for example when someone secretly made me a chocolate cake.
But when my car battery unexpectedly died and I'm late for an important
appointment then I get mad about it. Well either way I was surprised but I
believed that one surprise was good and one surprise was bad.

#+HTML: <!--more-->

Maybe sometimes a surprise is just a surprise? Take away the feelings about
the surprise and it really tones it down. It turns a surprise into an event.
And probably it is an event that must be dealt with in a timely manner. For
example either eat the cake before somebody else eats it or pull out the
jumper cables and get some help making your car run again. Both are events and
they must be handled in a timely manner. That is the key. They are important
and we feel something about them.

Important is an adjective describing things of great consequence. In other
words they must be dealt with now. Not at some point in the future. \laquo{}Now<\raquo{}.
For me the difference between \laquo{}feelings\raquo{} and \laquo{}important\raquo{} starts to really
stand out. This is where the difference between how you want to live your life
versus how you want feel about doing it floats to the surface.

\laquo{}Feelings\raquo{} guide your decision making process about things of no great
consequence.

\laquo{}Importance\raquo{} guides your decision making process for decisions of great
consequence.

So why perform any actions and make decisions about them unless they are of
great consequence? Because we are free to do so. We can decide though how we
want to spend all of our time acting upon things of either of greater or
lesser importance. Feel good and do nothing about the flat tire? Sure. Feel
bad and do nothing about the flat tire? You can. Both have great consequence.
And as much as I love chocolate cake, it doesn't matter much if it gets eaten
or not (never tell me this when I am hungry). We can choose whatever we wish.
The chance here is to study the different outcomes of making decisions based
on their \laquo{}importance\raquo{} compared with how we are \laquo{}feeling\raquo{} about them and see
what we prefer and when. Take it as an experiment.
