#+BLOG: wisdomandwonder
#+POSTID: 10595
#+ORG2BLOG:
#+DATE: [2017-07-10 Mon 09:51]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Happiness,
#+TITLE: Passion & Compassion. Action & Compaction.

Your passions are the things that you know in your heart that every one ought
to experience. The feeling inside your heart when you find humanity without
them, where it drives you to act, inspire and serve them to achieve it
themselves is compassion. Compassion is passion's companion.

Action is everything. Action is the difference between trying and not trying,
so at least do something. Action is the nature of this universe, it's physics
and our responsibility to the world. Compaction takes your values and beliefs,
distills them to their most simple and essential form. It is the crucible that
takes you from undecided to emboldened to not only believe but also to act
with complete conviction. Compaction is actions companion. Compaction
illuminates your core beliefs so what you share is true. So now
emboldened by your heart and your conscience.
