#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10629
#+DATE: [2017-07-30 Sun 15:23]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Happiness,
#+TITLE: The Opposite of Forget Is Mindful Not Remember

When you forget a \laquo{}person/place/thing/idea/though/memory\raquo{}, that which
previously sat in your cognitive field is there no longer. When you become
mindful of that \laquo{}person/place/thing/idea/though/memory\raquo{} again, it returns to
your cognitive field. We call this "forgetting and remembering" something. But
remember is the wrong word.

#+HTML: <!--more-->

Remember is the opposite of dismember. Dismember means to break apart into its
different parts or components. You can dismember countries and organizations
and ideas and aspects of personality and memories of events. Memories of
events are the most important for this example. Our definition of remember is
really composed of two parts: becoming mindful about those memories and
reassembling them into something useful.

Becoming mindful of memories sounds like a nonsensical statement but it is
simple: take memories that were somewhere else and bring them here. Sometimes
that happens consciously, intentionally and easily but other times it is an
unconscious process that was completely unplanned and out of your control.
Either way they came back. Becoming mindful of them simply means acknowledging
there presence. Whether it was in your control or not, what you do next is 00%
in your control: choosing how to re-member them.

Remembering those events means first choosing to focus on them or not.
Sometimes they are not worth pondering and you can let them move on. Others
are so intense and mesmerizing taking you do the depths of despair or the
elevations of ecstasy that there is no way you can get out of the tail-spin of
those feelings. The trick is to pull out of the tail-spin before starting to
re-member them.

Breathing comes naturally to all of us. Either we are doing it or not.
However, we can do it better. Doing it better creates a completely stable and
safe cognitive environment where we can place our memories in and out of our
cognitive field as we sit. It is a gentle process that lets us examine them
without the emotional charge. This process of re-membering without the massive
rush becomes a process full of curiosity and observation.

This is the true process of remembering that every human being ought to be
able to practice if they wish.
