#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10550
#+DATE: [2017-04-30 Sun 19:14]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Yoga, philosophy, Health, Happiness,
#+TITLE: You Must Do The Thing Which You Think You Cannot Do

Inspiration gives everything it has and expects nothing in return.

Here are five expansive and inclusive inspirations:

#+HTML: <!--more-->

#+BEGIN_QUOTE
You can gain strength, courage, and confidence by every experience in which you
really stop to look fear in the face...

You must do the thing which you think you cannot do.

-- Eleanor Roosevelt
#+END_QUOTE

Don't you want to be that person?

#+BEGIN_QUOTE
The place to improve the world is first in one's own heart and head and hands.

-- Robert M. Persig
#+END_QUOTE

Do you lead by example?

#+BEGIN_QUOTE
Thousands of candles can be lighted from a single candle, and the life of the
candle will not be shortened.

Happiness never decreases by being shared.

-- Buddha
#+END_QUOTE

It is never too late to be kind, right?

#+BEGIN_QUOTE
What you are looking for is what is looking.

-- St. Francis of Assisi
#+END_QUOTE

When is the last time that you heard someone say "That guy is looking for
happiness!"?

#+BEGIN_QUOTE
Your vision will become clear only when you look into your heart.

Who looks outside, dreams.

Who looks inside, awakens.

-- Carl Jung
#+END_QUOTE

Can we learn from what is inside us?
