#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10778
#+DATE: [2018-07-05 Thu 16:22]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Happiness, Health, philosophy, Yoga
#+TITLE: (Happiness) Recovering From Conversations that Have Gone Totally Wrong

My friend has a [[https://aliveandhealthy.us2.list-manage.com/track/click?u=58f0864c9904e2c3363c97238&id=5a16792735&e=9e7d96d44b][free lecture]] tonight. It is about dealing conversations that go
totally wrong. For example, you start out having a nice conversation over the
4th of July weekend and next thing you know the topic of favorite football
teams come up. Things just went from casual to serious. Then since the
conversation is already going so well somebody changes it to public policies
regarding controversial topics. Things just went from serious to critical.
Ouch, that isn't what anybody intended, but it is easy to recover from this.

My friend has a [[https://aliveandhealthy.us2.list-manage.com/track/click?u=58f0864c9904e2c3363c97238&id=5a16792735&e=9e7d96d44b][free lecture]] tonight about how to turn these really intense
and downright angry conversations back to where they began: two passionate
people who want to share what they value and feel with people who they respect
and care for. Check out how—it is possible for all of us immediately.
