#+ORG2BLOG:
#+BLOG: wisdomandwonder
#+POSTID: 10813
#+DATE: [2018-12-05 Wed 13:37]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Article
#+TAGS: Babel, Emacs, Ide, Lisp, Literate Programming, Programming Language, Reproducible research, elisp, org-mode
#+TITLE: (Emacs+Org-Mode) Share Links To Emacs Initialization Files With Minimal Effort!

I love reading all kinds of Emacs configuration files ranging for super
refined to just starting out. For example [[https://github.com/caisah/emacs.dz][caisah]] has a list of loads of
stellar examples. However the only way to get added to that list is for your
configuration to be notable. That is a pretty high bar for people just
starting out. New people also usually have the freshest ideas though and they
challenge the status quo of what we currently consider "the best". All of
those perspectives are valuable so I wanted to create a simple list that can
include all of them.

#+HTML: <!--more-->

[[https://github.com/grettke/every-emacs-initialization-file][Here]] it is.

So far I put my favorites in there. Since caisah's list /is/ so stellar, I would
probably import those next. After that I'm most curious about configurations
that either don't use any packages from ELPA, or that were written for old
Emacs versions maybe version 23 and below.
