#+BLOG: wisdomandwonder
#+POSTID: 12851
#+ORG2BLOG:
#+DATE: [2019-11-06 Wed 09:20]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Happiness
#+TAGS: Happiness
#+TITLE: Movement as Medicine?

Preemptive happiness management means doing it before you get miserable. But hey if you are like most of us you only do the work after you can't tolerate the misery anymore (seconds/minutes/hours/days/months/years) lol. This seminar is about the best easiest most efficient way to feel good again and what it does is gives you some momentum. You take it home with you. Use it to build the next thing and next thing. Your foundations gets stronger. You end up having more interesting things in life surprising things. Then visit again :).

[[https://www.facebook.com/himalayaninstitute/videos/1504425493041528/][Here]] is a video introduction and [[https://www.himalayaninstitute.org/event/movement-as-medicine-winter-2019/][here]] are the details.

Movement as Medicine works?

Yes absolutely.

[[https://www.himalayaninstitute.org/presenter/theresa-oswald-md/][Dr. Theresa Oswald, MD]] is the real deal. Absolutely worth your time money attention and every resource you value.

Hope you have a great trip.
